remote_theme: samarsault/plainwhite-jekyll

plainwhite:
  name: Di Wu
  tagline: Assistant Professor
  date_format: "%b %-d, %Y"

  social_links:
    twitter: samarsault
    github: samarsault
    linkedIn: in/samarsault # format: locale/username
  
  sitemap: true
  
  condensed_mobile:
    - home
    - post
    - page
    
  dark_mode: true

  search: true
